FROM public.ecr.aws/lambda/python:3.11

COPY pyproject.toml ${LAMBDA_TASK_ROOT}/
COPY src/ ${LAMBDA_TASK_ROOT}/src/

RUN pip install --no-cache-dir ${LAMBDA_TASK_ROOT}/ && \
    pip install --no-cache-dir boto3==1.35.0

CMD ["pipeshift.agent.handler"]
